FROM ruby:3.2-slim

WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev libffi-dev libyaml-dev

COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'production'
RUN bundle install

COPY . .

EXPOSE 3000

ENTRYPOINT ["./bin/docker-entrypoint"]
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
